services:
  backend:
    build: .
    container_name: backend
    command: node server.js
    ports:
      - "5000:5000"
    environment:
<<<<<<< HEAD
      - VITE_GEMINI_API_KEY=AIzaSyBlwN7kJrhSV6xCtGut9GeN4vYYhUEOfUw
=======
      - VITE_GEMINI_API_KEY=AIzaSyDn9eQea9xu6ZQMPVTjAEQilZtS7AO0zNs
>>>>>>> eed69394807e552815bb2dee00f16b7efbb9ad01

  frontend:
    build: .
    container_name: frontend
    command: npm run dev -- --host 0.0.0.0 --port 4173
    ports:
      - "4173:4173"
    depends_on:
      - backend